"""
Django settings for spaceaiusbe project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(-+q)hwi9jzosk(c3i)m-^j&1v2j+&=nu5h^9npxqa+=_$(&=g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]  # Allow all hosts for development, change in production


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'UserFunctions',
    "corsheaders",
    "paymentapp",
    "orders",
    "slab",
]

CORS_ALLOW_ALL_ORIGINS = False  # Disable allowing all origins
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Allow your frontend origin
    "https://pixmintai.com/",
    "http://pixmintai.com/"
]
CORS_ALLOW_CREDENTIALS = True

AUTH_USER_MODEL = 'UserFunctions.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'spaceaiusbe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spaceaiusbe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'spaceaius',
#         'USER': 'root',
#         'PASSWORD': 'root',
#         'HOST': 'localhost',  # or IP address
#         'PORT': '3306'
#         # 'OPTIONS': {
#         #     'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         # }
#     }
# }

# MYSQL_CONNECTOR_CONFIG = {
#     'host': 'localhost',
#     'user': 'root',
#     # 'password': 'Ov#050863',
#     'password': 'root',
#     'database': 'spaceaius',
# }

MYSQL_CONNECTOR_CONFIG = {
    'host': 'localhost',
    'user': 'primexio_pixmintai',
    'password': 'iknBQ6hn*TR=,p0A',
    'database': 'spaceaius',
}

# LIVE DB
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'primexio_pixmintai',
        'USER': 'primexio_pixmintai',
        'PASSWORD': 'iknBQ6hn*TR=,p0A',
        'HOST': 'localhost',  # or IP address
        'PORT': '3306'
        # 'OPTIONS': {
        #     'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        # }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

BASE_PAYMENT_URL = "https://api.nowpayments.io"
PAYMENT_API_KEY = "6V0QX2E-E154T8T-HDDA66Q-E2JR8BH"
ORDER_CURRENCY = "USD"  # Default order currency, can be changed as needed
IPN_URL = "https://nowpayments.io"  # IPN callback URL for payment notifications
