# Generated by Django 5.2.4 on 2025-08-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField()),
                ('request_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('orderID', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('price_currency', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20)),
                ('pay_address', models.TextField()),
                ('price_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('pay_currency', models.CharField(max_length=10)),
            ],
        ),
    ]
