# Generated by Django 5.2.4 on 2025-07-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserFunctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usercode',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
