# Generated by Django 5.2.4 on 2025-07-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserFunctions', '0003_user_refarcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refarcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
