# Generated by Django 5.2.4 on 2025-08-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='order_status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('sending', 'Sending'), ('partially_paid', 'Partially Paid'), ('finished', 'Finished'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired')], max_length=20),
        ),
    ]
