# Generated by Django 5.2.4 on 2025-08-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slab_name', models.CharField(max_length=100)),
                ('slab_percentage', models.FloatField()),
                ('activate_status', models.BooleanField(default=True)),
            ],
        ),
    ]
