# Generated by Django 5.2.4 on 2025-08-01 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_currency', models.CharField(max_length=10)),
                ('pay_currency', models.CharField(max_length=10)),
                ('order_status', models.CharField(choices=[('waiting', 'Waiting'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('sending', 'Sending'), ('partially_paid', 'Partially Paid'), ('finished', 'Finished'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired')], max_length=20)),
                ('order_log', models.TextField()),
                ('payment_address', models.CharField(max_length=255)),
                ('api_log', models.TextField()),
            ],
        ),
    ]
