# Generated by Django 5.2.4 on 2025-08-08 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderhistory_api_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='order_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('sending', 'Sending'), ('partially_paid', 'Partially Paid'), ('finished', 'Finished'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='pay_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
