# Generated by Django 5.2.4 on 2025-08-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderhistory_order_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
