# Generated by Django 5.2.4 on 2025-08-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderhistory_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='pay_currency',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
